import type { AdminSection } from "./adminTypes";

export type AdminMockModule = {
  fields: string[];
  id: AdminSection;
  note?: string;
  purpose: string;
  rows: Array<Record<string, string>>;
  title: string;
};

export const MOCK_ADMIN_MODULE_IDS = [
  "skills",
  "position",
  "services",
  "clients",
  "projects",
  "contracts",
  "corporate_experience",
  "opportunities",
  "partners",
  "proposals",
  "business_operations",
  "lessons_learned",
  "methodologies",
] as const satisfies AdminSection[];

export const mockAdminModules: Partial<Record<AdminSection, AdminMockModule>> = {
  company_overview: {
    id: "company_overview",
    title: "Company Overview Reference Updates",
    purpose:
      "High-level executive summary additions for the living company profile. These can remain concise while linking to more detailed operational modules later.",
    fields: ["Section", "Content"],
    rows: [
      { Section: "Quality Management", Content: "TriMerge is committed to delivering high-quality professional services through a structured quality management approach that emphasizes planning, independent review, continuous improvement, and client satisfaction. Quality processes incorporate technical reviews, document quality control, compliance verification, risk management, and lessons learned to ensure consistent, accurate, and timely deliverables." },
      { Section: "Corporate Differentiators", Content: "CPA expertise combined with management consulting; experience serving federal, state, local government, nonprofit, and commercial clients; specialized expertise in accounting, audit, grants, finance, emergency management, technology, and organizational consulting; flexible delivery model with internal professionals, subject matter experts, and strategic partners; AI-driven organizational intelligence through TriMergeIQ; strong workforce development through internships, universities, and mentoring." },
      { Section: "Strategic Partnerships", Content: "TriMerge maintains strategic partnerships with federal contractors, technology providers, universities, nonprofit organizations, staffing firms, and specialized consulting organizations to expand capabilities, strengthen proposal teams, and deliver comprehensive solutions across multiple industries and disciplines." },
      { Section: "Corporate Milestones", Content: "Founded in 2003; CPA and management consulting firm established; expanded into federal, state, and local government consulting; awarded multiple statewide professional services contracts; developed the TriMerge Innovation Lab; launched TriMergeIQ, TriMergePRO, and TriMerge Comply as strategic technology platforms." },
      { Section: "Future Vision", Content: "TriMerge seeks to become a nationally recognized professional services and technology consulting firm combining subject matter expertise, artificial intelligence, data-driven decision-making, and innovative workforce solutions to improve performance, strengthen governance, and achieve measurable results while developing the next generation of professionals." },
    ],
  },
  skills: {
    id: "skills",
    title: "Skills Management Mockup",
    purpose:
      "Centralized skills library for technical, professional, industry, software, regulatory, and leadership competencies used across staff, positions, services, projects, proposals, recruiting, and AI search.",
    fields: [
      "Skill Name",
      "Category",
      "Description",
      "Keywords",
      "Related Services",
      "Related Positions",
      "Proficiency Levels",
      "Certifications",
      "Software/Tools",
      "Industry Usage",
      "Regulatory References",
      "Notes",
    ],
    rows: [
      { Category: "Accounting & Financial Management", Examples: "Accounting, Financial Management, Governmental Accounting, Fund Accounting, Financial Reporting, Budget Development, Budget Monitoring, Cost Allocation Plans, Indirect Cost Rate Development, Payroll, Accounts Payable, Accounts Receivable, Treasury Management, Fixed Assets, General Ledger, Bank Reconciliations, Financial Analysis, Internal Controls, Capital Asset Management, Debt Management" },
      { Category: "Audit & Compliance", Examples: "Internal Audit, External Audit Support, Single Audit, Yellow Book Auditing, Compliance Monitoring, Risk Assessment, Fraud Investigations, Forensic Accounting, Corrective Action Plans, Internal Controls, Policy Development, Audit Readiness, Quality Assurance Reviews" },
      { Category: "Grants Management", Examples: "Federal Grants Management, State Grants Management, Grant Compliance, Grant Monitoring, Grant Closeout, Grant Reporting, Reimbursement Requests, Subrecipient Monitoring, Cost Principles, Allowable Costs" },
      { Category: "Program & Project Management", Examples: "Project Management, Program Management, PMO Development, Scheduling, Deliverable Tracking, Risk Management, Stakeholder Management, Change Management, Resource Planning, Agile, Waterfall" },
      { Category: "Emergency Management", Examples: "FEMA Public Assistance, FEMA Hazard Mitigation, Disaster Recovery, Debris Management, Emergency Operations, Recovery Planning, Damage Assessment, Hazard Mitigation Planning" },
      { Category: "Procurement & Government Contracting", Examples: "Federal Acquisition Regulations (FAR), DFARS, Proposal Development, Capture Management, Contract Administration, Source Selection, Vendor Management, Cost Proposal Development, Price Analysis, Market Research, Procurement Planning" },
      { Category: "Human Resources & Workforce Development", Examples: "Recruitment, Talent Acquisition, Workforce Development, Internship Programs, Training, Performance Management, Employee Relations, Organizational Development, Succession Planning" },
      { Category: "Technology", Examples: "Artificial Intelligence, Machine Learning, Knowledge Management, Organizational Intelligence, Business Intelligence, Software Development, Web Development, Systems Integration, Database Design, API Integration, Cloud Computing, Cybersecurity, Information Security, Identity & Access Management, Data Governance, Microsoft 365, SharePoint, Power BI" },
      { Category: "Data Analytics", Examples: "Data Analysis, Dashboard Development, Business Analytics, Performance Metrics, Data Visualization, Predictive Analytics, KPI Development" },
      { Category: "Leadership & Consulting", Examples: "Executive Leadership, Strategic Planning, Organizational Assessment, Facilitation, Executive Coaching, Business Process Improvement, Strategic Advisory, Governance" },
      { Category: "Regulatory & Standards", Examples: "2 CFR Part 200 (Uniform Guidance), Government Auditing Standards (Yellow Book), GAAP, GASB, OMB Uniform Guidance, Stafford Act, CDBG, ARPA, CARES Act, HIPAA, IRS Regulations" },
      { Category: "Software & Platforms", Examples: "QuickBooks, Deltek Costpoint, Deltek Ajera, Tyler Technologies, Oracle, SAP, Workday, Microsoft Office, Excel, Power BI, Tableau, Laserfiche, ArcGIS, SharePoint, Salesforce" },
      { Category: "Industry Expertise", Examples: "Federal Government, State Government, Local Government, Higher Education, Nonprofits, Healthcare, Utilities, Manufacturing, Transportation, Economic Development" },
      { Category: "Languages", Examples: "English, Spanish, Haitian Creole, French" },
      { Category: "Security & Clearances", Examples: "Security Clearance Management, Personnel Security, Facility Security, HSPD-12, Secret Clearance, Top Secret Clearance, Information Security, Data Privacy, Cybersecurity Governance" },
    ],
    note:
      "Each skill should become an individual editable record and the master dictionary referenced by staff, positions, services, projects, proposals, and recruiting.",
  },
  position: {
    id: "position",
    title: "Position Management Mockup",
    purpose:
      "Centralized position library for internal roles, consultants, contractors, proposal positions, recruiting positions, labor categories, and workforce planning.",
    fields: [
      "Position Title",
      "Position Code",
      "Position Category",
      "Department / Practice Area",
      "Position Summary",
      "Primary Responsibilities",
      "Required Skills",
      "Preferred Skills",
      "Minimum Education",
      "Minimum Experience",
      "Certifications",
      "Security Clearance",
      "Software Proficiency",
      "Industry Experience",
      "Reporting Relationship",
      "Supervisory Responsibilities",
      "Travel Requirements",
      "Work Arrangement",
      "Employment Type",
      "FLSA Status",
      "Labor Category",
      "Billable",
      "Position Status",
      "Notes",
    ],
    rows: [
      { Category: "Executive Leadership", Examples: "President & Chief Executive Officer, Chief Operating Officer, Chief Financial Officer, Chief Technology Officer, Director of Operations, Director of Workforce Development, Director of Business Development, Director of Innovation" },
      { Category: "Accounting & Finance", Examples: "Chief Financial Officer, Finance Director, Controller, Accounting Manager, Senior Accountant, Staff Accountant, Grant Accountant, Cost Accountant, Payroll Specialist, Accounts Payable Specialist, Accounts Receivable Specialist, Financial Analyst, Budget Analyst, Internal Auditor" },
      { Category: "Audit & Compliance", Examples: "Internal Auditor, Senior Auditor, Compliance Manager, Compliance Specialist, Risk Management Specialist, Quality Assurance Manager, Internal Control Analyst, Fraud Examiner, Forensic Accountant" },
      { Category: "Grants Management", Examples: "Grants Manager, Grant Administrator, Grant Compliance Specialist, Grant Accountant, Grant Monitor, Program Analyst" },
      { Category: "Program & Project Management", Examples: "Program Director, Program Manager, Project Manager, Project Coordinator, PMO Manager, PMO Analyst, Business Analyst, Management Consultant" },
      { Category: "Human Resources & Workforce", Examples: "Human Resources Manager, Recruiter, Talent Acquisition Specialist, Workforce Development Coordinator, Training Coordinator, Internship Program Manager, Career Coach" },
      { Category: "Technology", Examples: "Chief Technology Officer, IT Director, Systems Administrator, Network Administrator, Database Administrator, Software Developer, Full Stack Developer, Front-End Developer, Back-End Developer, AI Engineer, Machine Learning Engineer, Data Engineer, Business Intelligence Developer, Cybersecurity Specialist, Information Security Analyst, Systems Analyst, Solutions Architect" },
      { Category: "Data & Analytics", Examples: "Data Analyst, Business Intelligence Analyst, Data Scientist, GIS Analyst, Reporting Analyst" },
      { Category: "Administrative Support", Examples: "Executive Assistant, Administrative Assistant, Office Manager, Administrative Specialist, Receptionist, Document Control Specialist" },
      { Category: "Government Consulting", Examples: "Management Consultant, Financial Consultant, Procurement Consultant, Acquisition Specialist, Contract Specialist, Emergency Management Consultant, Public Assistance Specialist, Hazard Mitigation Specialist" },
      { Category: "Internships", Examples: "Accounting Intern, IT Intern, AI Research Intern, Software Development Intern, Data Analytics Intern, Business Development Intern, Marketing Intern, Government Consulting Intern" },
    ],
    note:
      "Positions should exist once and then be reused by recruiting, proposals, staffing, labor categories, and workforce planning.",
  },
  staff: {
    id: "staff",
    title: "Recruiting & Talent Management Mockup",
    purpose:
      "Extends Staff Management into a searchable talent and workforce planning module for candidates, consultants, SMEs, interns, advisors, and talent pipelines.",
    fields: [
      "Candidate Name",
      "Personnel Type",
      "Position(s)",
      "Practice Area",
      "Skills",
      "Years of Experience",
      "Education",
      "Certifications",
      "Security Clearance",
      "Location",
      "Employment Status",
      "Resume",
      "Source",
      "Recruiter",
      "Availability",
      "Rate / Salary",
      "Proposal(s)",
      "Contract(s)",
      "Interview Status",
      "Background Check",
      "References",
      "Notes",
      "Documents",
    ],
    rows: [
      { Category: "Accounting & Finance", Examples: "Accountants, financial analysts, controllers, grant accountants, audit professionals" },
      { Category: "Audit", Examples: "Internal auditors, external audit support, compliance reviewers, quality reviewers" },
      { Category: "IT", Examples: "Systems administrators, developers, help desk, technology consultants" },
      { Category: "Cybersecurity", Examples: "Cybersecurity specialists, information security analysts, clearance-aware security resources" },
      { Category: "AI & Data Analytics", Examples: "AI engineers, data analysts, business intelligence developers, data scientists" },
      { Category: "Project Management", Examples: "Project managers, project coordinators, PMO analysts" },
      { Category: "Program Management", Examples: "Program managers, program analysts, delivery leads" },
      { Category: "Grants Management", Examples: "Grant managers, grant monitors, grant compliance specialists" },
      { Category: "Emergency Management", Examples: "FEMA public assistance, hazard mitigation, disaster recovery resources" },
      { Category: "Engineering", Examples: "Engineering SMEs and technical consultants" },
      { Category: "Environmental Sciences", Examples: "Environmental SMEs and technical advisors" },
      { Category: "Healthcare", Examples: "Healthcare consultants, clinical study support, compliance resources" },
      { Category: "Human Resources", Examples: "Recruiters, HR managers, workforce development coordinators" },
      { Category: "Administrative Support", Examples: "Administrative specialists, executive assistants, document control" },
      { Category: "Acquisition & Procurement", Examples: "Contract specialists, acquisition specialists, procurement consultants" },
      { Category: "Logistics", Examples: "Logistics and operational support resources" },
      { Category: "Training", Examples: "Training coordinators, technical assistance providers, instructors" },
      { Category: "Executive Leadership", Examples: "Senior advisors, executives, directors, practice leaders" },
    ],
    note:
      "This is shown under Staff Management to avoid adding a separate Recruiting sidebar item until the backend supports candidate records.",
  },
  services: {
    id: "services",
    title: "Services Management Mockup",
    purpose:
      "Centralized service catalog for TriMerge service offerings, linked to skills, positions, industries, proposals, staffing, and knowledge retrieval.",
    fields: ["Service Name", "Service Category", "Service Description", "Related Skills", "Related Positions", "Industries Served", "Status"],
    rows: [
      { "Service Name": "Financial Management", "Service Category": "Finance & Accounting" },
      { "Service Name": "Accounting Services", "Service Category": "Finance & Accounting" },
      { "Service Name": "Tax Compliance & Consulting", "Service Category": "Finance & Accounting" },
      { "Service Name": "Audit Support", "Service Category": "Finance & Accounting" },
      { "Service Name": "Grants Management", "Service Category": "Grants & Compliance" },
      { "Service Name": "Program Management", "Service Category": "Program & Project Management" },
      { "Service Name": "Project Management", "Service Category": "Program & Project Management" },
      { "Service Name": "Compliance & Internal Controls", "Service Category": "Governance, Risk & Compliance" },
      { "Service Name": "Organizational & Management Consulting", "Service Category": "Management Consulting" },
      { "Service Name": "Strategic Planning", "Service Category": "Management Consulting" },
      { "Service Name": "Government Consulting", "Service Category": "Government Services" },
      { "Service Name": "Workforce Development", "Service Category": "Workforce Solutions" },
      { "Service Name": "Technology Consulting", "Service Category": "Technology & Innovation" },
      { "Service Name": "Artificial Intelligence & Organizational Intelligence", "Service Category": "Technology & Innovation" },
      { "Service Name": "Data Analytics & Business Intelligence", "Service Category": "Technology & Innovation" },
      { "Service Name": "Proposal Development & Capture Support", "Service Category": "Business Development" },
      { "Service Name": "Procurement & Acquisition Support", "Service Category": "Government Services" },
      { "Service Name": "Emergency Management", "Service Category": "Emergency Management" },
      { "Service Name": "Economic & Community Development", "Service Category": "Community Development" },
      { "Service Name": "Training & Technical Assistance", "Service Category": "Professional Services" },
      { "Service Name": "Risk Management", "Service Category": "Governance, Risk & Compliance" },
      { "Service Name": "Business Process Improvement", "Service Category": "Management Consulting" },
      { "Service Name": "Methodologies & Playbooks", "Service Category": "Knowledge & Delivery Standards" },
    ],
  },
  clients: {
    id: "clients",
    title: "Clients Management Mockup",
    purpose:
      "Centralized directory of current, former, and prospective clients for relationship management, proposals, projects, contracts, and organizational knowledge.",
    fields: ["Client Name", "Client Type", "Industry", "Government Level", "Tax-Exempt Classification", "Parent Organization", "State/Location", "Primary Contact", "Services Provided", "Contract Status", "Status", "Notes"],
    rows: [
      { "Client Name": "U.S. Department of Agriculture (USDA)", "Client Type": "Federal Government", Affiliation: "Federal Agency" },
      { "Client Name": "U.S. Department of Defense (DoD)", "Client Type": "Federal Government", Affiliation: "Federal Agency" },
      { "Client Name": "U.S. Department of Homeland Security (DHS)", "Client Type": "Federal Government", Affiliation: "Federal Agency" },
      { "Client Name": "U.S. Department of the Treasury", "Client Type": "Federal Government", Affiliation: "Federal Agency" },
      { "Client Name": "U.S. Agency for International Development (USAID)", "Client Type": "Federal Government", Affiliation: "Federal Agency" },
      { "Client Name": "State of Florida", "Client Type": "State Government", Affiliation: "State Government" },
      { "Client Name": "Florida Division of Emergency Management (FDEM)", "Client Type": "State Government", Affiliation: "State Agency" },
      { "Client Name": "Florida Department of Commerce", "Client Type": "State Government", Affiliation: "State Agency" },
      { "Client Name": "Miami-Dade County", "Client Type": "County Government", Affiliation: "County Government" },
      { "Client Name": "Miami-Dade Office of the Commission Auditor", "Client Type": "County Government", Affiliation: "Miami-Dade County Department" },
      { "Client Name": "City of Miami", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "City of Opa-locka", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "City of Deerfield Beach", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "City of Oakland Park", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "North Bay Village", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "Town of Bay Harbor Islands", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "Town of Loxahatchee Groves", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "City of St. Cloud", "Client Type": "Municipal Government", Affiliation: "Municipal Government" },
      { "Client Name": "Miami-Dade College", "Client Type": "Educational Institution", Affiliation: "Public Educational Institution" },
      { "Client Name": "Little Haiti Revitalization Trust", "Client Type": "Nonprofit Organization", Affiliation: "Component Unit of the City of Miami" },
      { "Client Name": "Panam Sports", "Client Type": "Nonprofit Organization", Affiliation: "501(c)(6)" },
      { "Client Name": "Prodev", "Client Type": "Nonprofit Organization", Affiliation: "501(c)(3)" },
      { "Client Name": "Pilates Method Alliance", "Client Type": "Nonprofit Organization", Affiliation: "501(c)(3)" },
      { "Client Name": "Alliance of Supplier Diversity Professionals (ASDP)", "Client Type": "Nonprofit Organization", Affiliation: "501(c)(3)" },
      { "Client Name": "Doctor Aroma's", "Client Type": "Private Sector", Affiliation: "Commercial Entity" },
      { "Client Name": "Miami Heat (Basketball Properties, LP)", "Client Type": "Private Sector", Affiliation: "Commercial Entity" },
      { "Client Name": "State of Florida", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "DC Water", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "FDA", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "Defense Health Agency", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "Bank of America", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "SBA", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
      { "Client Name": "GSA", "Client Type": "CRM Organization", Affiliation: "Relationship Management" },
    ],
    note:
      "Relationship Management (CRM) content is folded into Clients Management for now: organizations and contacts can later become separate linked record types.",
  },
  projects: {
    id: "projects",
    title: "Projects Management Mockup",
    purpose:
      "Centralized repository for client engagements, contracts, task orders, projects, and internal initiatives, linked to clients, services, staff, skills, and documents.",
    fields: ["Project Name", "Project Number", "Client", "Contract", "Task Order", "Project Type", "Service(s)", "Project Manager", "Project Team", "Practice Area", "Start Date", "End Date", "Contract Value", "Funding Source", "Project Status", "Description", "Scope of Work", "Key Deliverables", "Key Milestones", "Technologies Used", "Skills Required", "Related Documents", "Lessons Learned", "Status"],
    rows: [
      { "Project Name": "City of Opa-locka Financial Recovery & Grant Management", Client: "City of Opa-locka", "Project Type": "Financial Management" },
      { "Project Name": "City of Deerfield Beach Interim Financial Management", Client: "City of Deerfield Beach", "Project Type": "Financial Management" },
      { "Project Name": "Bay Harbor Islands Interim Finance Director Services", Client: "Town of Bay Harbor Islands", "Project Type": "Financial Management" },
      { "Project Name": "Miami-Dade Office of the Commission Auditor Audit Support", Client: "Miami-Dade Office of the Commission Auditor", "Project Type": "Audit" },
      { "Project Name": "Little Haiti Revitalization Trust Financial Statement Audit", Client: "Little Haiti Revitalization Trust", "Project Type": "Audit" },
      { "Project Name": "North Bay Village Financial Consulting", Client: "North Bay Village", "Project Type": "Financial Management" },
      { "Project Name": "City of Oakland Park FY2027 Budget Development", Client: "City of Oakland Park", "Project Type": "Financial Management" },
      { "Project Name": "Doctor Aroma's Forensic Accounting Investigation", Client: "Doctor Aroma's", "Project Type": "Forensic Accounting" },
      { "Project Name": "Miami Heat Financial Consulting Services", Client: "Miami Heat (Basketball Properties, LP)", "Project Type": "Financial Consulting" },
      { "Project Name": "TriMergeIQ Platform Development", Client: "Internal", "Project Type": "Technology" },
      { "Project Name": "TriMergePRO Workforce Platform", Client: "Internal", "Project Type": "Technology" },
      { "Project Name": "EPIC Workforce Development Internship Program", Client: "Internal", "Project Type": "Workforce Development" },
    ],
  },
  contracts: {
    id: "contracts",
    title: "Contracts Management Mockup",
    purpose:
      "Centralized repository for contracts and consulting engagements, helping track current and past work while supporting project management and proposals.",
    fields: ["Contract Name", "Client", "Contract Type", "Prime or Subcontract", "Services Provided", "Start Date", "End Date", "Contract Status", "Project Manager", "Notes"],
    rows: [
      { "Contract Name": "State of Florida - Management Consulting Services", Client: "State of Florida", "Contract Type": "Prime Contract", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "State of Florida - Information Technology Staff Augmentation", Client: "State of Florida", "Contract Type": "Prime Contract", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "Florida Department of Commerce - Management Consulting Services", Client: "Florida Department of Commerce", "Contract Type": "Prime Contract", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "City of Opa-locka - Financial Management Services", Client: "City of Opa-locka", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "City of Deerfield Beach - Interim Financial Management Services", Client: "City of Deerfield Beach", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "City of Deerfield Beach - Temporary Staffing Services", Client: "City of Deerfield Beach", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "Town of Bay Harbor Islands - Interim Finance Director Services", Client: "Town of Bay Harbor Islands", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "North Bay Village - Financial Consulting Services", Client: "North Bay Village", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "City of North Miami Beach - SOP Development & Budget Support Services", Client: "City of North Miami Beach", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "City of Miami Beach - Audit Support Services", Client: "City of Miami Beach", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "Miami-Dade Office of the Commission Auditor - Professional Audit Services", Client: "Miami-Dade Office of the Commission Auditor", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "Little Haiti Revitalization Trust - Annual Financial Statement Audit", Client: "Little Haiti Revitalization Trust", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "City of Oakland Park - Budget Consulting Services", Client: "City of Oakland Park", "Contract Type": "Professional Services Agreement", "Prime/Sub": "Prime", Status: "Closed" },
      { "Contract Name": "Doctor Aroma's - Forensic Accounting & Investigation Services", Client: "Doctor Aroma's", "Contract Type": "Consulting Agreement", "Prime/Sub": "Prime", Status: "Open" },
      { "Contract Name": "Miami Heat (Basketball Properties, LP) - Annual Inventory Audit Consulting Project", Client: "Miami Heat (Basketball Properties, LP)", "Contract Type": "Consulting Agreement", "Prime/Sub": "Prime", Status: "Open" },
    ],
  },
  corporate_experience: {
    id: "corporate_experience",
    title: "Corporate Experience Mockup",
    purpose:
      "Searchable past-performance library for completed and ongoing engagements across public, private, nonprofit, and international sectors.",
    fields: ["Engagement Title", "Client", "Parent Organization", "Industry", "Practice Area", "Services Provided", "Prime or Subcontractor", "Period of Performance", "Contract Status", "Reference Available", "Reference Contact", "Summary of Work", "Key Results", "Keywords", "Supporting Documents", "Status"],
    rows: [
      { "Engagement Title": "Financial Recovery & Grant Management", Client: "City of Opa-locka", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Interim Financial Management Services", Client: "City of Deerfield Beach", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Temporary Staffing Services", Client: "City of Deerfield Beach", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Interim Finance Director Services", Client: "Town of Bay Harbor Islands", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Financial Consulting Services", Client: "North Bay Village", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "SOP Development & Budget Support Services", Client: "City of North Miami Beach", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Audit Support Services", Client: "City of Miami Beach", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Professional Audit Services", Client: "Miami-Dade Office of the Commission Auditor", Role: "Prime", Industry: "County Government" },
      { "Engagement Title": "Annual Financial Statement Audit", Client: "Little Haiti Revitalization Trust", Role: "Prime", Industry: "Nonprofit Organization" },
      { "Engagement Title": "Budget Consulting Services", Client: "City of Oakland Park", Role: "Prime", Industry: "Municipal Government" },
      { "Engagement Title": "Annual Inventory Audit Consulting", Client: "Miami Heat (Basketball Properties, LP)", Role: "Prime", Industry: "Private Sector" },
      { "Engagement Title": "Forensic Accounting & Investigation", Client: "Doctor Aroma's", Role: "Prime", Industry: "Private Sector" },
      { "Engagement Title": "Outsourced Controller & Financial Management Services", Client: "Alonzo Mourning Charities", Role: "Prime", Industry: "Nonprofit Organization" },
      { "Engagement Title": "Financial Management, Accounting & Audit Support Services", Client: "Virginia Key Beach Park Trust", Role: "Prime", Industry: "Nonprofit Organization (Component Unit of the City of Miami)" },
      { "Engagement Title": "Ocean Outfall Legislation Program Support", Client: "CH2M / Miami-Dade Water & Sewer Department", Role: "Subcontractor", Industry: "Water & Wastewater" },
      { "Engagement Title": "Cost & Price Analysis Support", Client: "USAID Mexico", Role: "Subcontractor", Industry: "International Development" },
      { "Engagement Title": "Financial Management & Technical Assistance", Client: "Centers for Disease Control and Prevention (CDC)", Role: "Prime/Subcontractor", Industry: "Federal Government" },
      { "Engagement Title": "Audit & Audit Support Services", Client: "Broward Housing", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Housing" },
      { "Engagement Title": "Resort Tax Audit Services", Client: "City of Miami Beach", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Municipal Government" },
      { "Engagement Title": "Financial Statement Audit", Client: "Florida Memorial University", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Higher Education" },
      { "Engagement Title": "Financial Statement Audit", Client: "Legal Services of Greater Miami", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Nonprofit Organization" },
      { "Engagement Title": "Financial Statement Audit", Client: "Downtown Development Authority", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Special District / Authority" },
      { "Engagement Title": "Financial Statement Audit", Client: "City of Oakland Park", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Municipal Government" },
      { "Engagement Title": "Financial Statement Audit", Client: "Early Learning Coalition of Broward County", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Nonprofit Organization" },
      { "Engagement Title": "CRA Audit Support & Audit Readiness", Client: "City of Opa-locka Community Redevelopment Agency", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Municipal Government" },
      { "Engagement Title": "Incurred Cost Audit Support Services", Client: "Multiple Government Contractors", Role: "Subcontractor (BCA Watson Rice LLP)", Industry: "Federal Government" },
      { "Engagement Title": "Financial Statement Audit", Client: "Caribbean Hotel & Tourism Association (CHTA)", Role: "Prime", Industry: "Nonprofit Organization" },
      { "Engagement Title": "Financial Statement Audit", Client: "North Carolina Black Alliance", Role: "Prime", Industry: "Nonprofit Organization" },
    ],
  },
  opportunities: {
    id: "opportunities",
    title: "Opportunity & Capture Management Mockup",
    purpose:
      "Centralized repository for business development opportunities, capture activities, proposals, strategic pursuits, and internal initiatives from identification through award or closeout.",
    fields: ["Opportunity Name", "Solicitation Number", "Client / Agency", "Opportunity Type", "Practice Area", "Owner", "Teaming Partners", "Prime or Subcontract", "Stage", "Status", "Priority", "Due Date", "Estimated Value", "Next Action", "Outcome / Disposition", "Notes", "Documents"],
    rows: [
      { Opportunity: "State of Florida - Management Consulting Services", "Client / Agency": "State of Florida", Stage: "Awarded", Status: "Closed", Priority: "Critical", Outcome: "Awarded" },
      { Opportunity: "State of Florida - IT Staff Augmentation", "Client / Agency": "State of Florida", Stage: "Awarded", Status: "Closed", Priority: "High", Outcome: "Awarded" },
      { Opportunity: "Florida Department of Commerce - Management Consulting", "Client / Agency": "Florida Department of Commerce", Stage: "Awarded", Status: "Closed", Priority: "Critical", Outcome: "Awarded" },
      { Opportunity: "Miami-Dade County Contract Employee Services", "Client / Agency": "Miami-Dade County", Stage: "Submitted", Status: "Active", Priority: "Critical", Outcome: "Pending" },
      { Opportunity: "DC Water - IT Professional Services", "Client / Agency": "DC Water", Stage: "Proposal Development", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "DC Water - Financial Consulting Services", "Client / Agency": "DC Water", Stage: "Proposal Development", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "CDRH Clinical Study Services Contract", "Client / Agency": "FDA", Stage: "Proposal Development", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "G1 PASS Professional & Administrative Support Services", "Client / Agency": "U.S. Army", Stage: "Capture", Status: "Active", Priority: "Critical", Outcome: "Pending" },
      { Opportunity: "DHA OMNIBUS IV", "Client / Agency": "Defense Health Agency", Stage: "Capture", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "USGS Scientific & Technical Support IDIQ", "Client / Agency": "U.S. Geological Survey", Stage: "Submitted", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "Bureau of Land Management Administrative & Technical Support", "Client / Agency": "Bureau of Land Management", Stage: "Submitted", Status: "Active", Priority: "Medium", Outcome: "Pending" },
      { Opportunity: "FMCS Travel Compliance Services", "Client / Agency": "FMCS", Stage: "Submitted", Status: "Active", Priority: "Medium", Outcome: "Pending" },
      { Opportunity: "City of Oak Hill Professional Consulting Services", "Client / Agency": "City of Oak Hill", Stage: "Submitted", Status: "Active", Priority: "Medium", Outcome: "Pending" },
      { Opportunity: "Palm Beach County Human Resources Audit", "Client / Agency": "Palm Beach County", Stage: "Awaiting Decision", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "Jessie Trice Community Health System", "Client / Agency": "Jessie Trice Community Health System", Stage: "Awaiting Decision", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "IT Help Desk Services", "Client / Agency": "Enspyre", Stage: "Awaiting Decision", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "IRS Digital Services", "Client / Agency": "IRS / Enspyre", Stage: "Awaiting Decision", Status: "Active", Priority: "High", Outcome: "Pending" },
      { Opportunity: "SBA Manufacturing Opportunity", "Client / Agency": "U.S. Small Business Administration", Stage: "Awaiting Decision", Status: "Active", Priority: "Medium", Outcome: "Pending" },
      { Opportunity: "FDA Ergonomics Support Services", "Client / Agency": "FDA", Stage: "Closeout", Status: "Closed", Priority: "Medium", Outcome: "Lost - Price" },
      { Opportunity: "FDEM Hazard Mitigation Assistance Technical Support Services", "Client / Agency": "Florida Division of Emergency Management", Stage: "Closeout", Status: "Closed", Priority: "High", Outcome: "Not Awarded" },
      { Opportunity: "NATO IPSAS Financial Advisory Services", "Client / Agency": "NATO", Stage: "Closeout", Status: "Closed", Priority: "Medium", Outcome: "Cancelled - Set-Aside Changed" },
      { Opportunity: "USSOCOM POTFF Support Services", "Client / Agency": "USSOCOM / Leidos", Stage: "Teaming", Status: "On Hold", Priority: "High", Outcome: "Pending" },
      { Opportunity: "Dell Laptop Refresh / Technology Acquisition", "Client / Agency": "Internal", Stage: "Proposal Development", Status: "Active", Priority: "Medium", Outcome: "Pending" },
    ],
  },
  partners: {
    id: "partners",
    title: "Partner Management Mockup",
    purpose:
      "Centralized repository for strategic partners, subcontractors, joint venture partners, consultants, universities, nonprofits, staffing partners, and technology partners that collaborate with TriMerge.",
    fields: ["Partner Name", "Partner Type", "Business Classification", "Primary Contact", "Website", "Headquarters", "Industries", "Practice Areas", "Core Capabilities", "Certifications", "Contract Vehicles", "Geographic Coverage", "Security Clearance Capability", "Past Teaming History", "Active Opportunities", "NDA Executed", "Teaming Agreement Executed", "Status", "Notes", "Documents"],
    rows: [
      { "Partner Name": "St. Michael's Inc.", "Partner Type": "Strategic Partner" },
      { "Partner Name": "Enspyre", "Partner Type": "Strategic Partner" },
      { "Partner Name": "SpatialGIS", "Partner Type": "Strategic Partner" },
      { "Partner Name": "H3C", "Partner Type": "Strategic Partner" },
      { "Partner Name": "Arthur Group", "Partner Type": "Strategic Partner" },
      { "Partner Name": "ZIO Technologies", "Partner Type": "Strategic Partner" },
      { "Partner Name": "Comcentia", "Partner Type": "Strategic Partner" },
      { "Partner Name": "JT Facility Solutions", "Partner Type": "Strategic Partner" },
      { "Partner Name": "Hawes Consulting Group", "Partner Type": "Strategic Partner" },
      { "Partner Name": "BCA Watson Rice LLP", "Partner Type": "Strategic Partner" },
      { "Partner Name": "CLA (CliftonLarsonAllen)", "Partner Type": "Strategic Partner" },
      { "Partner Name": "Microsoft", "Partner Type": "Technology Partner" },
      { "Partner Name": "OpenAI", "Partner Type": "Technology Partner" },
      { "Partner Name": "Vercel", "Partner Type": "Technology Partner" },
      { "Partner Name": "Netlify", "Partner Type": "Technology Partner" },
      { "Partner Name": "Miami-Dade College", "Partner Type": "University / Workforce" },
      { "Partner Name": "Miami Tech Works", "Partner Type": "University / Workforce" },
      { "Partner Name": "Duane Mathis", "Partner Type": "Independent Consultant" },
      { "Partner Name": "David Ritchey", "Partner Type": "Independent Consultant" },
      { "Partner Name": "Helen Boller", "Partner Type": "Independent Consultant" },
      { "Partner Name": "Marcelo (DA)", "Partner Type": "Independent Consultant" },
    ],
    note:
      "Partner records should later link to opportunities, proposals, contracts, corporate experience, staff, notes, capability statements, certifications, NDAs, and teaming agreements.",
  },
  proposals: {
    id: "proposals",
    title: "Proposal Management Mockup",
    purpose:
      "Centralized repository for proposal planning, writing, reviewing, submitting, archiving, reusable content, and institutional proposal knowledge.",
    fields: ["Proposal Name", "Related Opportunity", "Solicitation Number", "Client / Agency", "Proposal Manager", "Capture Manager", "Technical Lead", "Pricing Lead", "Contracts Administrator", "Team Members", "Proposal Type", "Submission Method", "Due Date", "Submission Date", "Status", "Proposal Result", "Lessons Learned", "Proposal Documents"],
    rows: [
      { "Proposal Name": "Miami-Dade County Contract Employee Services", Status: "In Development" },
      { "Proposal Name": "DC Water - IT Professional Services", Status: "In Development" },
      { "Proposal Name": "DC Water - Financial Consulting Services", Status: "In Development" },
      { "Proposal Name": "CDRH Clinical Study Services", Status: "In Development" },
      { "Proposal Name": "G1 PASS", Status: "Capture" },
      { "Proposal Name": "DHA OMNIBUS IV", Status: "Capture" },
      { "Proposal Name": "USGS Scientific & Technical Support", Status: "Submitted" },
      { "Proposal Name": "Palm Beach County HR Audit", Status: "Awaiting Decision" },
      { "Proposal Name": "City of Oak Hill", Status: "Submitted" },
      { "Proposal Name": "SBA Manufacturing Opportunity", Status: "Awaiting Decision" },
      { "Proposal Name": "FMCS Travel Compliance", Status: "Submitted" },
      { "Proposal Name": "Bureau of Land Management Administrative Support", Status: "Submitted" },
    ],
    note:
      "This complements Proposal Hub but is shown in Admin as a management mockup for proposal records, milestones, roles, lessons learned, and documents.",
  },
  business_operations: {
    id: "business_operations",
    title: "Business Operations Management Mockup",
    purpose:
      "Central repository for internal operations, administrative activities, compliance, vendor management, technology assets, and corporate initiatives.",
    fields: ["Initiative Name", "Category", "Owner", "Department", "Priority", "Status", "Start Date", "Target Completion Date", "Budget", "Related Vendor", "Related Asset", "Notes", "Documents"],
    rows: [
      { "Initiative Name": "Dell Laptop Refresh", Category: "Equipment Procurement" },
      { "Initiative Name": "Microsoft 365 Administration", Category: "Software Licensing" },
      { "Initiative Name": "TriMergeIQ Development", Category: "Technology" },
      { "Initiative Name": "TriMergePRO Development", Category: "Technology" },
      { "Initiative Name": "TriMerge Comply Development", Category: "Technology" },
      { "Initiative Name": "GSA Schedule Application", Category: "Business Development" },
      { "Initiative Name": "Facility Clearance (FCL) Preparation", Category: "Compliance" },
      { "Initiative Name": "Quality Management Program", Category: "Strategic Initiatives" },
      { "Initiative Name": "Website Modernization", Category: "Marketing" },
      { "Initiative Name": "ADA Website Compliance", Category: "Compliance" },
      { "Initiative Name": "Marketing & Brand Development", Category: "Marketing" },
      { "Initiative Name": "LinkedIn Content Strategy", Category: "Marketing" },
      { "Initiative Name": "Internship & Workforce Development Program", Category: "Workforce Development" },
      { "Initiative Name": "AI Innovation Lab", Category: "Innovation Lab" },
      { "Initiative Name": "Vendor Management Program", Category: "Vendor Management" },
      { "Initiative Name": "Insurance & Corporate Compliance Tracking", Category: "Corporate Administration" },
    ],
  },
  lessons_learned: {
    id: "lessons_learned",
    title: "Lessons Learned & Continuous Improvement Mockup",
    purpose:
      "Central repository for successes, challenges, best practices, risks, corrective actions, and recommendations from proposals, contracts, projects, audits, business development, and internal initiatives.",
    fields: ["Lesson Title", "Category", "Source", "Related Opportunity", "Related Proposal", "Related Project", "Related Contract", "Related Client", "Practice Area", "Date Identified", "Description", "Root Cause", "Recommendation", "Action Taken", "Responsible Owner", "Priority", "Status", "Supporting Documents", "Keywords"],
    rows: [
      { Lesson: "Maintain a pricing database for future proposals.", Category: "Proposal Development" },
      { Lesson: "Begin recruiting specialized SMEs earlier in the capture process.", Category: "Recruiting" },
      { Lesson: "Maintain a reusable corporate experience library.", Category: "Proposal Development" },
      { Lesson: "Record agency debriefings immediately after award decisions.", Category: "Business Development" },
      { Lesson: "Build stronger incumbent intelligence during capture.", Category: "Capture Management" },
      { Lesson: "Expand strategic partner database by capability area.", Category: "Partner Management" },
    ],
  },
  methodologies: {
    id: "methodologies",
    title: "Methodologies & Playbooks Mockup",
    purpose:
      "Central repository for standardized methodologies, delivery frameworks, playbooks, SOPs, workflows, checklists, and best practices.",
    fields: ["Methodology / Playbook Name", "Category", "Practice Area", "Service", "Description", "Purpose", "Applicable Industries", "Related Skills", "Related Positions", "Process Steps", "Deliverables", "Tools & Technologies", "Templates", "Related Documents", "Owner", "Version", "Status", "Last Updated", "Notes"],
    rows: [
      { "Methodology / Playbook Name": "Federal Capture Management Process", Category: "Business Development" },
      { "Methodology / Playbook Name": "Proposal Development Process", Category: "Business Development" },
      { "Methodology / Playbook Name": "Opportunity Evaluation Framework", Category: "Business Development" },
      { "Methodology / Playbook Name": "Go / No-Go Decision Process", Category: "Business Development" },
      { "Methodology / Playbook Name": "Partner Evaluation Process", Category: "Business Development" },
      { "Methodology / Playbook Name": "Client Onboarding Process", Category: "Project Management" },
      { "Methodology / Playbook Name": "Project Kickoff Framework", Category: "Project Management" },
      { "Methodology / Playbook Name": "Project Status Reporting", Category: "Project Management" },
      { "Methodology / Playbook Name": "Project Closeout Process", Category: "Project Management" },
      { "Methodology / Playbook Name": "Financial Assessment Methodology", Category: "Accounting & Finance" },
      { "Methodology / Playbook Name": "Budget Development Methodology", Category: "Accounting & Finance" },
      { "Methodology / Playbook Name": "Internal Control Assessment", Category: "Accounting & Finance" },
      { "Methodology / Playbook Name": "Cost Allocation Plan Methodology", Category: "Accounting & Finance" },
      { "Methodology / Playbook Name": "Indirect Cost Rate Methodology", Category: "Accounting & Finance" },
      { "Methodology / Playbook Name": "Financial Statement Audit Methodology", Category: "Audit" },
      { "Methodology / Playbook Name": "Internal Audit Methodology", Category: "Audit" },
      { "Methodology / Playbook Name": "Performance Audit Methodology", Category: "Audit" },
      { "Methodology / Playbook Name": "Fraud Investigation Methodology", Category: "Audit" },
      { "Methodology / Playbook Name": "Forensic Accounting Methodology", Category: "Audit" },
      { "Methodology / Playbook Name": "FEMA Public Assistance Delivery Framework", Category: "Emergency Management" },
      { "Methodology / Playbook Name": "Hazard Mitigation Program Support Methodology", Category: "Emergency Management" },
      { "Methodology / Playbook Name": "Disaster Recovery Consulting Framework", Category: "Emergency Management" },
      { "Methodology / Playbook Name": "AI Readiness Assessment", Category: "Technology" },
      { "Methodology / Playbook Name": "Technology Modernization Framework", Category: "Technology" },
      { "Methodology / Playbook Name": "Data Governance Assessment", Category: "Technology" },
    ],
    note:
      "This is linked to Services Management conceptually, but it needs its own mock page because it stores repeatable delivery processes and playbooks, not service offerings.",
  },
};
